---
# This playbook contains common plays that will be run on all nodes.
##

- name: Create mongo_bak_dir
  shell: mkdir -p {{ mongo_bak_dir }}/$(date '+%F_%H')
  tags: mongo

- name: Backup MongoDB by mongodump
  shell: /usr/bin/mongodump --host {{ mongo_host }} --port {{ mongo_port }} --db {{ mongo_db }} --out $(date '+%F_%H')
  args:
    chdir: "{{ mongo_bak_dir }}"
  tags: mongo
  
 
- name: Starting Backup, Create backup dir 
  shell: mkdir -p {{ dmp_bak_dir }}/$(date '+%F_%H')/data-suite/
  tags:
     - always
     - backup 

- name: Backup audience_api
  shell: \cp -ar {{ dmp_dir }}/audience_api {{ dmp_bak_dir }}/$(date '+%F_%H')/
 # copy: src={{ dmp_dir }}/audience_api dest={{ dmp_bak_dir }}/$(date '+%F_%H')/audience_api remote_src=yes 
  tags: 
     - backup
     - audience_api

- name: Backup data-assets-report-api
  shell: \cp -ar {{ dmp_dir }}/data-assets-report-api {{ dmp_bak_dir }}/$(date '+%F_%H')/
  tags:
     - backup
     - data-assets-report-api

- name: Backup datapi
  shell: \cp -ar {{ dmp_dir }}/datapi {{ dmp_bak_dir }}/$(date '+%F_%H')/
  tags:
     - backup
     - dataapi

- name: Backup analytics 
  shell: \cp -ar {{ data_suite_dir }}/analytics {{ dmp_bak_dir }}/$(date '+%F_%H')/data-suite/
  tags:
     - backup
     - analytics 

- name: Backup data-assets
  shell: \cp -ar {{ data_suite_dir }}/data-assets {{ dmp_bak_dir }}/$(date '+%F_%H')/data-suite/
  tags:
     - backup
     - data-assets

- name: Backup upm 
  shell: \cp -ar {{ data_suite_dir }}/upm {{ dmp_bak_dir }}/$(date '+%F_%H')/data-suite/
  tags:
     - backup
     - upm

- name: Backup audience 
  shell: \cp -ar {{ data_suite_dir }}/audience {{ dmp_bak_dir }}/$(date '+%F_%H')/data-suite/
  tags:
     - backup
     - audience 

- name: Backup crm 
  shell: \cp -ar {{ data_suite_dir }}/crm {{ dmp_bak_dir }}/$(date '+%F_%H')/data-suite/
  tags:
     - backup
     - crm 

- name: Backup ba
  shell: \cp -ar {{ data_suite_dir }}/ba-studio {{ dmp_bak_dir }}/$(date '+%F_%H')/data-suite/
  tags:
     - backup
     - ba

- name: Starting deploy, Create deploy dir 
  shell: mkdir -p {{ dmp_deploy_dir }}/$(date '+%F_%H')
  tags:
     - always

      
##
- name: Copy local deploy file to server's temp dir
  copy: src={{ item }} dest={{ dmp_deploy_dir }} mode=0755
  with_items:
    - web_webapps.zip
    - file
    - sql
  tags:
     - always 
     - file

- name: Stop audience_api service
  shell: "{{ item }}"
  args:
    chdir: "{{ audience_api_dir }}"
  with_items:
    - "sh stop.sh all"
  tags: 
     - stop
     - audience_api

- name: stop datapi services
  shell: "{{ item }}"
  args: 
    chdir: "{{ datapi_dir }}"
  with_items: 
    - "sh stop.sh"
  tags: 
     - stop
     - datapi

- name: stop data-assets-report-api service
  shell: "{{ item }}"
  args: 
    chdir: "{{ data_assets_report_api_dir }}"
  with_items: 
    - "sh stop.sh"
  tags: 
     - stop
     - data-assets-report-api


- name: Unarchive webapps.zip 
#  unarchive: src={{ dmp_deploy_dir }}/web_webapps.zip dest=/mnt copy=no mode=0755
  shell: unzip -od /mnt {{ dmp_deploy_dir }}/web_webapps.zip
  tags: always


- name: Start audience_api service
  shell: "{{ item }}"
  args:
    chdir: "{{ audience_api_dir }}"
  with_items:
    - "chmod -R a+x ."
    - "setsid sh start.sh all"
  tags: 
     - start
     - audience_api

- name: start datapi services
  shell: "{{ item }}"
  args: 
    chdir: "{{ datapi_dir }}"
  with_items: 
    - "chmod -R a+x ."
    - "setsid sh app.sh all"
  tags: 
     - start
     - datapi

- name: start data-assets-report-api service
  shell: "{{ item }}"
  args: 
    chdir: "{{ data_assets_report_api_dir }}"
  with_items: 
    - "chmod -R a+x ."
    - "setsid sh start.sh all"
  tags: 
     - start
     - data-assets-report-api


# analytics config
- name: Copy analytics last config file
  shell: \cp -ar {{ dmp_bak_dir }}/$(date '+%F_%H')/data-suite/analytics/{{ webapi_conf }} {{ data_suite_dir }}/analytics/{{ webapi_conf }}
  tags:
     - config
     - analytics 

# audience config
- name: Copy audience last config file
  shell: \cp -ar {{ dmp_bak_dir }}/$(date '+%F_%H')/data-suite/audience/{{ webapi_conf }} {{ data_suite_dir }}/audience/{{ webapi_conf }}
  tags:
     - config
     - audience 

# data-assets  config
- name: Copy data-assets last config file
  shell: \cp -ar {{ dmp_bak_dir }}/$(date '+%F_%H')/data-suite/data-assets/{{ webapi_conf }} {{ data_suite_dir }}/data-assets/{{ webapi_conf }}
  tags:
     - config
     - data-assets 

# upm config
- name: Copy upm last config file
  shell: \cp -ar {{ dmp_bak_dir }}/$(date '+%F_%H')/data-suite/upm/{{ webapi_conf }} {{ data_suite_dir }}/upm/{{ webapi_conf }}
  tags:
     - config
     - upm

# crm config
- name: Copy crm last config file
  shell: \cp -ar {{ dmp_bak_dir }}/$(date '+%F_%H')/data-suite/crm/{{ webapi_conf }} {{ data_suite_dir }}/crm/{{ webapi_conf }}
  tags:
     - config
     - crm

# ba config
- name: Copy ba last config file
  shell: \cp -ar {{ dmp_bak_dir }}/$(date '+%F_%H')/data-suite/ba/{{ webapi_conf }} {{ data_suite_dir }}/ba/{{ webapi_conf }}
  tags:
     - config
     - ba

- name: confirmation audience-api file date 
  shell: ls -l {{item}}
  register: audience-api_date
  args:
    chdir: /mnt/webapps/audience-api/
  with_items:
    - business-api/businessapi
    - business-api/businessservice
    - business-cron/businesscron
    - data-api/dataapi
    - data-api/dataservice
    - data-cron/datacron
    - download-api/downloadapi
    - third-iresearch/server 
  tags: 
     - confirm
     - audience-api

- debug: var=audience-api_date
  tags: 
     - confirm
     - audience-api

- name: confirmation datapi file date 
  shell: ls -l {{item}}
  register: datapi_date
  args:
    chdir: "{{ datapi_dir }}"
  with_items:
    - datasource
  tags: 
     - confirm
     - datapi

- debug: var=datapi_date
  tags: 
     - confirm
     - datapi

- name: confirmation data-assets-report-api file date 
  shell: ls -l {{item}}
  register: dataassetsreportapi_date
  args:
    chdir: "{{ data_assets_report_api_dir }}"
  with_items:
    - data-assets-reportapi
  tags: 
     - confirm
     - data-assets-report-api

- debug: var=dataassetsreportapi_date
  tags: 
     - confirm
     - data-assets-report-api


- name: confirmation upm file date 
  shell: ls -l {{item}}
  register: upm_date
  args:
    chdir: /mnt/webapps/data-suite/upm/
  with_items:
    - webapi
    - webapp/index.html
  tags: 
     - confirm
     - upm

- debug: var=upm_date
  tags: 
     - confirm
     - upm

- name: confirmation analytics file date 
  command: ls -l {{item}}
  register: analytics_date
  args:
    chdir: /mnt/webapps/data-suite/analytics/
  with_items:
    - webapi
    - webapp/index.html
  tags: 
     - confirm
     - analytics
- debug: var=analytics_date
  tags: 
     - confirm
     - analytics

- name: confirmation audience file date 
  command: ls -l {{item}}
  register: audience_date
  args:
    chdir: /mnt/webapps/data-suite/audience/
  with_items:
    - webapi
    - webapp/index.html
  tags: 
     - confirm
     - audience

- debug: var=audience_date
  tags: 
     - confirm
     - audience

- name: confirmation crm file date 
  command: ls -l {{item}}
  register: crm_date
  args:
    chdir: /mnt/webapps/data-suite/crm/
  with_items:
    - webapi
    - webapp/index.html
  tags: 
     - confirm
     - crm

- debug: var=crm_date
  tags: 
     - confirm
     - crm

- name: confirmation ba file date 
  command: ls -l {{item}}
  register: ba_date
  args:
    chdir: /mnt/webapps/data-suite/ba-studio/
  with_items:
    - webapi
    - webapp/index.html
  tags: 
     - confirm
     - ba

- debug: var=ba_date
  tags: 
     - confirm
     - ba

- name: confirmation data-assets file date 
  command: ls -l {{item}}
  register: dataassets_date
  args:
    chdir: /mnt/webapps/data-suite/data-assets/
  with_items:
    - webapi
    - webapp/index.html
  tags: 
     - confirm
     - data-assets

- debug: var=dataassets_date
  tags: 
     - confirm
     - data-assets


- name: update upm npm packages
  shell: npm i
  register: upm_npm
  args:
    chdir: /mnt/webapps/data-suite/upm/webapi
  tags: 
     - upm_npm

- debug: var=upm_npm
  tags: 
     - upm_npm
     

- name: restart upm process
  shell: /usr/local/bin/pm2 restart {{item}} && pm2 show upm-webapi | grep 'uptime' && pm2 show upm-webapi-local | grep 'uptime'
  with_items:
    - upm-webapi
    - upm-webapi-local
  register: upm_pm2
  tags: 
     - upm_pm2
- debug: var=upm_npm
  tags: 
     - upm_npm

- name: Archive deploy file
  shell: \mv {{ item }} $(date '+%F_%H')
  args:
    chdir: "{{ dmp_deploy_dir }}"
  ignore_errors: yes
  with_items:
    - web_webapps.zip
    - file/*
    - sql/*
  tags:
     - always
     - archive 


- name: Delete 60d ago backup file
  shell: cd {{ dmp_bak_dir }} && find . -mtime +60 -type d -print0 | xargs -0 /bin/rm -fr 
  tags: 
     - always
     - clean
   
- name: Delete 15d ago deploy file
  shell: cd {{ dmp_deploy_dir }} && find . -mtime +15 -type d -print0 | xargs -0 /bin/rm -fr 
  tags: 
     - always
     - clean
     
- name: Delete 60d ago mongo and mysql file 
  shell: cd {{item}} && find . -mtime +60 -print0 | xargs -0 /bin/rm -fr 
  with_items:
    - "{{ mongo_bak_dir }}"
  tags: 
     - mongo
     - clean


##  shell: \cp -ar {{ dmp_deploy_dir }}/$(date '+%F_%H')/data-suite/analytics/webapi/analytics-20170920/* {{ dmp_dir }}/data-suite/analytics/webapi
#- name: Restart webapi by pm2 
#  shell: /usr/local/bin/pm2 ls 
#  #shell: pm2 restart analytics-sync analytics-webapi
#
