---
# This playbook deploys the whole application stack in this site.  

## Apply common configuration to all hosts
#- hosts: all
#- hosts: artwee_report-api
- hosts: poli-demo-clone
#- hosts: qa_etl
#- hosts: azkaban
#- hosts: exxon_web
#- hosts: exxon_web-clone
#- hosts: iresearch_web
#- hosts: mc_web
#- hosts: pilot_web
  gather_facts: no
  serial: 1
  remote_user: xu.chen
  become: yes
  become_user: root
  roles:
#   - azkaban
  - web 

  tags:
  - web
#   - azkaban

