---
# This playbook contains common plays that will be run on all nodes.
- name: Create app dir on server
  shell: mkdir -p {{ app_dir }}
  #shell: mkdir -p {{ dmp_bak_dir }}/`date '+%F_%H'`/data-suite/analytics

#- name: Check node_exporter process 
#  command: pgrep node_exporter | wc -l 
#  register: node_exporter_status
#
#- debug:
#    msg: "node_exporter start failure"
#  when: node_exporter_status.stdout|int != 0

- name: Copy local node_exporter package to remote server
  copy: src=node_exporter-0.12.1.linux-amd64.tar.gz dest={{ app_dir }}/  

- name: Unarchive node_exporter package 
  unarchive:
    src: /mnt/apps/node_exporter-0.12.1.linux-amd64.tar.gz
    dest: /mnt/apps
    remote_src: yes

- name: Add node_exporter to rc.local 
  shell: mkdir -p textfile_collector && echo -e '\n# Start node_exporter \ncd {{ app_dir }}/node_exporter-0.12.1.linux-amd64 && setsid ./node_exporter -collector.textfile.directory textfile_collector -web.listen-address 0.0.0.0:9900 >> /var/log/node_exporter.log 2>&1 &' >> /etc/rc.d/rc.local
#  args:
#    chdir: "{{ app_dir }}/node_exporter-0.12.1.linux-amd64"

- name: Start node_exporter
  shell: source /etc/rc.d/rc.local

- name: Check node_exporter process 
  shell: pgrep node_exporter | wc -l 
  register: node_exporter_status

- debug:
    msg: "node_exporter start failure"
  when: node_exporter_status.stdout|int == 0



