---
# This playbook contains common plays that will be run on all nodes.
- name: Create app dir on server
  shell: mkdir -p {{ app_dir }}
  #shell: mkdir -p {{ dmp_bak_dir }}/`date '+%F_%H'`/data-suite/analytics

- name: Copy local node_exporter package to remote server
  copy: src=node_exporter-0.12.1.linux-amd64.tar.gz dest={{ app_dir }}/  

- name: Unarchive node_exporter package 
  unarchive:
    src: /mnt/apps/node_exporter-0.12.1.linux-amd64.tar.gz
    dest: /mnt/apps
    remote_src: yes

- name: add node_exporter auto-start  
  shell: echo -e '# Start node_exporter \nsetsid /mnt/apps/node_exporter-0.12.1.linux-amd64/node_exporter -web.listen-address 0.0.0.0:9900 >> /var/log/node_exporter.log 2>&1' >> /etc/rc.d/rc.local

#- name: start node_exporter
#  shell: source /etc/rc.d/rc.local



