---
# This playbook contains common plays that will be run on all nodes.
#
- name: Create backup dir 
  command: mkdir -p {{ dmp_bak_dir }}/$(date '+%F_%H')

# report-api
- name: Backup report-api
  command: \cp -ar {{ report_dir }} {{ dmp_bak_dir }}/$(date '+%F_%H')/

- name: Create deploy dir 
  command: mkdir -p {{ dmp_deploy_dir }}/$(date '+%F_%H')


- name: Copy local deploy file to server's temp dir
  copy: src=reportapi_webapps.zip dest={{ dmp_deploy_dir }} 
  

- name: Unarchive report webapps.zip 
#  shell: unzip -od /mnt {{ dmp_deploy_dir }}/reportapi_webapps.zip
  unarchive: src={{ dmp_deploy_dir }}/reportapi_webapps.zip dest=/mnt copy=no mode=0755


- name: Get reportapi processes id
  shell: pgrep reportapi 
  register: reportapi_pid

- name: Get reportcron processes id 
  shell: pgrep reportcron 
  register: reportcron_pid
#  ignore_errors: yes


- name: Stop reportapi , reportcron service 
  command: "{{ item }}"
  args: 
    chdir: "{{ report_dir }}"
  with_items: 
    - "sh stop.sh"
    - "sh stopjob.sh"

- name: Check reportapi processes 
  shell: pgrep reportapi| wc -l 
  register: reportapi_status

- name: Check reportcron processes 
  shell: pgrep reportapi| wc -l 
  register: reportcron_status

- name: If reportapi runing, force kill it
  shell: kill -9 reportapi_pid.stdout
  when: reportapi_status.stdout|int = 1

- name: If reportcron runing, force kill it
  shell: kill -9 reportcron_pid.stdout
  when: reportcron_status.stdout|int = 1


- name: Start reportapi , reportcron service 
  command: "{{ item }}" 
  args:
    chdir: "{{ report_dir }}"
  with_items: 
    - "sh start.sh"
    - "sh startjob.sh"


- command: echo 'reportapi start failure'
  when: reportapi_status.stdout|int != 1

- command: echo 'reportcron start failure'
  when: reportcron_status.stdout|int != 1


- name: Archive deploy file
  shell: mv {{ dmp_deploy_dir }}/reportapi_webapps.zip {{ dmp_deploy_dir }}/$(date '+%F_%H')/




