---
# This playbook contains common plays that will be run on all nodes.
#
- name: Create backup dir 
  shell: mkdir -p {{ dmp_bak_dir }}/$(date '+%F_%H')
  tags: always
# report-api
- name: Backup report-api
  shell: \cp -ar {{ report_dir }} {{ dmp_bak_dir }}/$(date '+%F_%H')/
  tags: always

- name: Create deploy dir 
  shell: mkdir -p {{ dmp_deploy_dir }}/$(date '+%F_%H')
  tags: always


- name: Copy local deploy file to server's temp dir
  copy: src=reportapi_webapps.zip dest={{ dmp_deploy_dir }} mode=0755
  tags: always
  

- name: Check reportapi processes pro
  shell: pgrep report | wc -l
  register: reportapi_status
  ignore_errors: yes
  tags: 
     - always

- name: Check reportcron processes pro
  shell: pgrep reportcron | wc -l 
  register: reportcron_status
  ignore_errors: yes
  tags: always


- name: Stop reportapi , reportcron service 
  shell: "{{ item }}"
  args: 
    chdir: "{{ report_dir }}"
  with_items: 
    - "sh stop.sh"
    - "sh stopjob.sh"
  ignore_errors: yes
  tags: 
     - stop
     - mc

#
- name: reportapi runing , force kill it
  shell: killall reportapi
  when: reportapi_status.stdout|int != 0 
  ignore_errors: yes
  tags: 
     - stop
     - mc

- name: reportcron runing , force kill it
  shell: killall reportcron
  when: reportcron_status.stdout|int != 0
  ignore_errors: yes
  tags: stop


- name: Unarchive report webapps.zip 
  shell: unzip -od /mnt {{ dmp_deploy_dir }}/reportapi_webapps.zip
  tags: mc
#  unarchive: src={{ dmp_deploy_dir }}/reportapi_webapps.zip dest=/mnt copy=no mode=0755


- name: Start reportapi , reportcron service 
  shell: "{{ item }}" 
  args:
    chdir: "{{ report_dir }}"
  with_items: 
    - "chmod a+x reportapi"
    - "chmod a+x reportcron"
    - "setsid sh start.sh"
    - "setsid sh startjob.sh"
  ignore_errors: yes
  tags: 
     - always

- name: Check reportapi processes post
  shell: pgrep reportapi | wc -l 
  register: reportapi_status
  tags: 
     - always

- name: Check reportcron processes post
  shell: pgrep reportcron | wc -l 
  register: reportcron_status
  tags: start

- debug:
    msg: "reportapi start failure"
  when: reportapi_status.stdout|int == 0
  tags: start

- debug:
    msg: "reportcron start failure"
  when: reportcron_status.stdout|int == 0
  tags: start

- name: confirmation report-api file date
  command: ls -l {{item}}
  register: report_date
  args:
    chdir: "{{ report_dir }}"
  with_items:
    - reportapi
    - reportcron
  tags: always

- debug: var=report_date
  tags: always
  ignore_errors: yes


- name: Archive deploy file
  shell: \mv reportapi_webapps.zip $(date '+%F_%H')/
  args:
    chdir: "{{ dmp_deploy_dir }}"
  tags: 
     - always


- name: Delete 60d ago backup file
  shell: cd {{ dmp_bak_dir }} && find . -mtime +60 -type d -print0 | xargs -0 /bin/rm -fr
  tags:
     - always
     - clean

- name: Delete 15d ago deploy file
  shell: cd {{ dmp_deploy_dir }} && find . -mtime +15 -type d -print0 | xargs -0 /bin/rm -fr
  tags:
     - always
     - clean
