---
# This playbook contains common plays that will be run on all nodes.
- name: Create app dir on server
  shell: mkdir -p {{ app_dir }}
  #shell: mkdir -p {{ dmp_bak_dir }}/`date '+%F_%H'`/data-suite/analytics

- name: Copy local telegraf package to remote server
  copy: src=telegraf-1.3.5-1.x86_64.rpm dest={{ app_dir }}/  

- name: Install telegraf package
  yum:
    name: /mnt/apps/telegraf-1.3.5-1.x86_64.rpm
    state: present

# Start telegraf 
- service:
    name: telegraf
    state: started 
  
- name: add telegraf auto-start  
  shell: chkconfig telegraf on 

#- name: start node_exporter
#  shell: source /etc/rc.d/rc.local



