---
# This playbook contains common plays that will be run on all nodes.

- name: Copy add_ssh_key.sh and all_ssh_key to remote server
  copy: src={{ item }} dest={{ dmp_deploy_dir }} mode=0755
  with_items:
    - all_ssh_key
    - add_ssh_key.sh
  tags:
    - install 
    - log_install 

- name: Start add ssh_key exec add_ssh_key.sh
  shell: "sh add_ssh_key.sh {{ ssh_user }}"
  args:
    chdir: "{{ dmp_deploy_dir }}"
  tags:
    - install 
    - log_install 

- name: Add sudo privileges 
  shell: echo "{{ ssh_user }} ALL=(ALL)       NOPASSWD:ALL" >> /etc/sudoers
  tags:
    - install 

- name: Add access log privileges
  shell: setfacl -Rm u:{{ ssh_user }}:rx {{ item }}
  ignore_errors: yes
  with_items:
    - /mnt/logs
    - /mnt/webapps/audience_api/log
  tags:
    - log_install
 



- name: Revoke access log privileges
  shell: setfacl -Rx u:{{ ssh_user }} {{ item }}
  ignore_errors: yes
  with_items:
    - /mnt/logs
    - /mnt/webapps/audience_api/log
  tags:
    - log_remove

- name: Delete username 
  shell: "userdel -r {{ ssh_user }}"
  tags:
    - remove
    - log_remove

- name: Delete username's sudo config
  shell: sed -i.bak "/^{{ ssh_user }}/d" {{ sudo_conf }}
  tags:
    - remove

