---
# This playbook contains common plays that will be run on all nodes.

- name: Copy add_ssh_key.sh and ssh_key to remote server
  copy: src={{ item }} dest={{ dmp_deploy_dir }} mode=0755
  with_items:
    - all_ssh_key
    - add_ssh_key.sh
  tags:
    - ssh 
    - key 

- name: Start add ssh_key exec add_ssh_key.sh
  shell: "sh add_ssh_key.sh loch.gu"
  args:
    chdir: "{{ dmp_deploy_dir }}"
  tags:
    - start 




